spring:
  kafka:
    streams:
      cleanup:
        on-startup: true
      application-id: my-id
    bootstrap-servers: kafka-content-01.test.cloud.croc-comp.goods.local:9092,kafka-content-02.test.cloud.croc-comp.goods.local:9092,kafka-content-03.test.cloud.croc-comp.goods.local:9092
